image: ubuntu:latest

push-to-dmm:
  stage: deploy
  script:
    - |
      apt-get update && apt-get install -y ca-certificates && apt-get install -y wget && apt-get install -y curl
      
      update-ca-certificates 
      wget -q https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64.tar.gz -O - |\
        tar xz && mv yq_linux_amd64 /usr/bin/yq

      id=$(yq .info.id dataproduct.yml)
      json=$(yq -o json dataproduct.yml)
      curl -X 'PUT' \
        "https://app.datamesh-manager.com/api/dataproducts/$id" \
        -H "accept: */*" \
        -H "x-api-key: $DATAPRODUCT_EXAMPLE_API_KEY" \
        -H "Content-Type: application/json" \
        -d "$json" \
        --fail
