name: Push Data Product To DMM
on:
  push:
  schedule:
    - cron: '0 10 * * *'
jobs:
  Push-Data-Product:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install yq
        uses: mikefarah/yq@v4.34.1
      - name: Push to DMM
        env: 
          API_KEY: ${{ secrets.DMM_API_KEY }}
        run: |
          id=$(yq .info.id dataproduct.yml)
          json=$(yq -o json dataproduct.yml)
          curl -X 'PUT' \
            "https://app.datamesh-manager.com/api/dataproducts/$id" \
            -H "accept: */*" \
            -H "x-api-key: $API_KEY" \
            -H "Content-Type: application/json" \
            -d "$json"
            --fail
